### ISSUE TITLE
Use Rows.Columns

### ISSUE THREAD

**Issue by paddycarver** [darlinggo/pan#4]
Rather than relying on ordering, I should use the [Rows.Columns](http://golang.org/pkg/database/sql/#Rows.Columns) API to return the names of the columns returned, then match them to the struct properties by name, not position.

This does mean that I can no longer use Unmarshal on *Row results, as *Row (for whatever reason) does not support Columns. C'est la vie.

**Comment by paddyforan** [comment]
Addressed in #7.
